const actionTypes = {

    GET: "GET"
    ,GET_BLOG_POSTS: "GET_BLOG_POSTS"
    ,GET_BLOG_POST_DETAILS: "GET_BLOG_POST_DETAILS"
    ,GET_BLOG_POST_CATEGORY_LIST: "GET_BLOG_POST_CATEGORY_LIST"
    ,GET_BLOG_POST_COMMENTS: "GET_BLOG_POST_COMMENTS"
    ,GET_BLOG_POSTS_SEARCH: "GET_BLOG_POSTS_SEARCH"
    ,GET_BLOG_POSTS_REFRESH: "GET_BLOG_POSTS_REFRESH"
    ,GET_BLOG_POST_DETAILS_LOADER: "GET_BLOG_POST_DETAILS_LOADER"
    ,GET_BLOG_POSTS_SEARCH_LOADER: "GET_BLOG_POSTS_SEARCH_LOADER"

}


export default actionTypes 