const actionTypes = {

    GET: "GET"
    , GET_BLOG_POSTS: "GET_BLOG_POSTS"
    , GET_BLOG_POST_DETAILS: "GET_BLOG_POST_DETAILS"
    , GET_BLOG_POST_CATEGORY_LIST: "GET_BLOG_POST_CATEGORY_LIST"
    , GET_BLOG_POST_CATEGORY_SELECT: "GET_BLOG_POST_CATEGORY_SELECT"
    , GET_BLOG_POST_CATEGORY_UNSELECT: "GET_BLOG_POST_CATEGORY_UNSELECT"
    , GET_BLOG_POST_CATEGORY_POSTS: "GET_BLOG_POST_CATEGORY_POSTS"
    , GET_BLOG_POST_COMMENTS: "GET_BLOG_POST_COMMENTS"
    , GET_BLOG_POSTS_SEARCH: "GET_BLOG_POSTS_SEARCH"
    , GET_BLOG_POSTS_REFRESH: "GET_BLOG_POSTS_REFRESH"
    , GET_BLOG_POST_DETAILS_LOADER: "GET_BLOG_POST_DETAILS_LOADER"
    , GET_BLOG_POSTS_SEARCH_LOADER: "GET_BLOG_POSTS_SEARCH_LOADER"
    , SET_THEME: "SET_THEME"
    , GET_BLOG_POSTS_LOADMORE: "GET_BLOG_POSTS_LOADMORE"
    , TOGGLE_POST_WEBVIEW: "TOGGLE_POST_WEBVIEW"
    , POST_POPUP: "POST_POPUP"

}


export default actionTypes 