const actionTypes = {

    GET: "GET"
    ,GET_BLOG_POSTS: "GET_BLOG_POSTS"
    ,GET_BLOG_POST_DETAILS: "GET_BLOG_POST_DETAILS"
    ,GET_BLOG_POST_COMMENTS: "GET_BLOG_POST_COMMENTS"
    ,GET_BLOG_POSTS_SEARCH: "GET_BLOG_POSTS_SEARCH"
    ,GET_BLOG_POSTS_REFRESH: "GET_BLOG_POSTS_REFRESH"

}


export default actionTypes 